### ISSUE TITLE
Supported Ivy features

### ISSUE THREAD

**Issue by Yuan-Mao** [aman-goel/ic3po#7]
Hi, thanks for the amazing tool!

I am using commit e44f6f9d7148f50af1745e519edca6d5e1f37369. I'm new to Ivy language and recently I have been trying out IC3PO to see if it can infer inductive invariants for my ivy specification. I have written a toy paxos.ivy and it can be parsed by Ivy 1.7. However, for some reason I can't get IC3PO to work on it.

Here's the paxos.ivy:
```
#lang ivy1.7

module total_order_with_zero(t) = {
    axiom (T:t < U & U < V) -> (T < V)  # Transitivity
    axiom ~(T:t < U & U < T)            # Anti-symmetry
    axiom T:t < U | T = U | U < T       # Totality
    axiom 0 <= X:t
}

type ballot
instantiate total_order_with_zero(ballot)

type acceptor
type proposer
type value
type quorum # majority


# Each ballot(proposal number) should correspond to only one proposer and one value
function get_proposer(B:ballot) : proposer
function get_value(B:ballot) : value

# Note that we only use axioms to describe the abstract characteristics 
# of 'member' instead of assigning any actual values to it
relation member(A:acceptor, Q:quorum)
axiom forall Q1, Q2. exists A. member(A, Q1) & member(A, Q2)


# For Acceptor: ballots that have already been accepted
relation accepted_ballots(A:acceptor, B:ballot)

# A ballot 'B' with value 'V' to acceptor 'A' has been sent out (but can be dropped)
relation ballot_is_sent(A:acceptor, B:ballot, V: value)

# Acceptor 'A' has sent an ack to the proposer that is responsible for ballot 'B'
relation sent_ack(A: acceptor, B:ballot)

after init {
    accepted_ballots(A, B) := false;
    # We want ballot number 0 (which is invalid ballot) stands out
    # when no valid ballot is accepted 
    accepted_ballots(A, 0) := true;
    ballot_is_sent(A, B, V) := false;
    sent_ack(A, B) := false;
}

####### For 1a #######

# There is no action for one_a. When IVy calls one_b it means some proposer has called
# one_a.

####### For 1b #######

# Acceptor 'a' receives a prepare request with number 'b'
# It's possible to accept duplicate ballot
action one_b(a:acceptor, current_promise:ballot, b:ballot) = {
    require 0 < b;
    require sent_ack(a, current_promise) & forall B:ballot. sent_ack(a, B)
        -> B <= current_promise | (current_promise = 0 & forall P. ~sent_ack(a, P));

    if(current_promise <= b) {
        sent_ack(a, b) := true;
    }
}

####### For 2a #######

# q: the quorum from which ACKs has been collected
# a, b, v: A proposer wants to send ballot 'b' to acceptor 'a'
# 'a' is not necessarily within the quorum
action two_a(a:acceptor, b:ballot, q:quorum, maxb:ballot) = {
    require forall A. (member(A, q) & sent_ack(A, b));
    # make sure maxb is really maxb
    require (exists A. (member(A, q) & accepted_ballots(A, maxb))) &
        (forall A1. member(A1, q) & forall B1. (accepted_ballots(A1, B1) -> B1 <= maxb));
    var maxb_val:value;
    # This has already included both case 1 where no accepted proposal has been accepted by a majority and
    # case 2 where some accepted proposals have been accepted
    # If maxb = 0, then the non-deterministic value from get_value is used.
    maxb_val := get_value(maxb);
    ballot_is_sent(a, b, maxb_val) := true;
}

action two_b(a:acceptor, b:ballot, v:value, current_promise:ballot) = {
    # Update accepted_ballots
    # Some proposer must have sent ballot 'b' to 'a' and 'b' must >= promise(a)
    require sent_ack(a, current_promise) & forall B:ballot. sent_ack(a, B)
        -> B <= current_promise | (current_promise = 0 & forall P. ~sent_ack(a, P));
    require (ballot_is_sent(a, b, v) & current_promise <= b);
    get_value(b) := v;
    accepted_ballots(a, b) := true;
}


####### Actions exported to the environment #######
export one_b
export two_a
export two_b

invariant forall B1, B2. (
                (exists Q. (forall A. member(A, Q) & accepted_ballots(A, B1))) &
                (exists Q. (forall A. member(A, Q) & accepted_ballots(A, B2)))
            ) -> get_value(B1) = get_value(B2)

```

And after running ic3po, I get:

```
> python2 ic3po.py -o foo -n bar ivy_paxos/paxos.ivy
------------------------------------------------------------------------
IC3PO: IC3 for Proving Protocol Properties
copyright (c) 2021  Aman Goel and Karem Sakallah, University of Michigan
------------------------------------------------------------------------

        (output dir: foo/bar)
        (frontend: ivy)
        (converting: ivy -> vmt)
Traceback (most recent call last):
  File "/root/ic3po/ic3po/ivy_to_vmt.py", line 599, in <module>
    main()
  File "/root/ic3po/ic3po/ivy_to_vmt.py", line 594, in main
    print_module()
  File "/root/ic3po/ic3po/ivy_to_vmt.py", line 574, in print_module
    print_isolate()
  File "/root/ic3po/ic3po/ivy_to_vmt.py", line 554, in print_isolate
    print_module_vmt(mod)
  File "/root/ic3po/ic3po/ivy_to_vmt.py", line 63, in __init__
    self.execute()
  File "/root/ic3po/ic3po/ivy_to_vmt.py", line 97, in execute
    self.process_actions()
  File "/root/ic3po/ic3po/ivy_to_vmt.py", line 348, in process_actions
    sf = self.standardize_action(f, update[0], name)
  File "/root/ic3po/ic3po/ivy_to_vmt.py", line 405, in standardize_action
    action = lgu.substitute(f, subs)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/logic_util.py", line 156, in substitute
    return type(t)(*(substitute(x, subs) for x in t))
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/logic_util.py", line 156, in <genexpr>
    return type(t)(*(substitute(x, subs) for x in t))
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/logic_util.py", line 166, in substitute
    raise CaptureError(forbidden_variables.intersection(t.variables))
ivy.logic_util.CaptureError
Traceback (most recent call last):
  File "ic3po.py", line 182, in <module>
    main()
  File "ic3po.py", line 138, in main
    raise Exception("conversion error: return code %d" % s)
Exception: conversion error: return code 1

```

My best guess is that I might have used some Ivy features that are not currently supported by the tool? Or maybe there are just some hidden problems in my Ivy code?

Any feedback or directions would be extremely helpful.

Thank you very much!

**Comment by aman-goel** [comment]
(Apologies for my super late response)

Thanks for raising the issue. IC3PO supports limited constructs from IVy version [d695423](https://github.com/aman-goel/ivy/tree/d695423946de0d0b0f3606da094ff5d856de6a7a). Most of these constructs appear in examples from [ivybench](https://github.com/aman-goel/ivybench) repository.

To make things worse, the error reporting of IC3PO isn't great either to catch parse errors.
As of now, there is no plan to actively add new upgrades to IC3PO frontend. :-(

One possibility is to extend the [ivy_to_vmt.py](https://github.com/aman-goel/ic3po/blob/master/ic3po/ivy_to_vmt.py) script to support additional IVy features.

The other possibility is to encode your examples with currently-supported constructs (e.g., replace `lhs <= rhs` with `le(lhs, rhs)`, `lhs > rhs` with `~le(lhs, rhs)`).
