### ISSUE TITLE
assertion failure on flash protocol example

### ISSUE THREAD

**Issue by kenmcmil** [aman-goel/ic3po#8]
[flash-plain.tgz](https://github.com/user-attachments/files/16881983/flash-plain.tgz)

ic3po stops with an assertion failure on the attached example. 

ic3po commit: 3104be6
platform: Intel Mac, MacOS 13.01
command line:
```
python ic3po.py -o foo -n bar flash-plain.ivy --size id=3
```
ic3po stdout:
```
----------------------------------------------------------------------------------
IC3PO: IC3 for Proving Protocol Properties
Copyright (c) 2018 - Present  Aman Goel and Karem Sakallah, University of Michigan
----------------------------------------------------------------------------------

	(output dir: foo/bar)
	(frontend: ivy)
	(converting: ivy -> vmt)
	(mode: ic3po)
	(reuse: 1)
	(opt: 1)
	(const: 1)
	(wires: 1)
	(using z3 4.8.9.0 with seed 1)
	(using yices 2.6.5 with seed 1)
	(epr: False)
	(gen: fef)
	(found #28 actions)
	(setting |id| to 3)

Finite sorts: #1
	|id| = 3
	(input is not in epr)
@     1s  0: 1 :1    
@     1s  1: 1 10 :11    
@     2s  2: 1 7 11 :19    
@     8s  3: 1 11 23 41 :76    
@    15s  4: 1 11 24 36 58 :130    
@    31s  5: 1 8 18 32 66 112 :237    
@    95s  6: 1 8 18 32 64 157 289 :569    
@   226s  7: 1 8 18 24 67 194 367 382 :1061    
Traceback (most recent call last):
  File "/Users/kenmcm/ic3po/ic3po/top.py", line 119, in <module>
    main()
  File "/Users/kenmcm/ic3po/ic3po/top.py", line 109, in main
    backwardReach(common.gopts.file, None)
  File "/Users/kenmcm/ic3po/ic3po/ic3po.py", line 4318, in backwardReach
    inv_set_l, cex = p.check_property(helpers)
  File "/Users/kenmcm/ic3po/ic3po/ic3po.py", line 2377, in check_property
    if self.recursive_block(len(self.frames)-1, cube, cubeV):
  File "/Users/kenmcm/ic3po/ic3po/ic3po.py", line 4064, in recursive_block
    res2 = self.recursive_block(i-1, cubepre, cubepreV)
  File "/Users/kenmcm/ic3po/ic3po/ic3po.py", line 4016, in recursive_block
    ucoreQ = symmetry_cube(self, ucore, i-1, True, cubeprime)
  File "/Users/kenmcm/ic3po/ic3po/problem.py", line 650, in symmetry_cube
    assert(len(cubesOut) != 0)
AssertionError
Traceback (most recent call last):
  File "ic3po.py", line 182, in <module>
    main()
  File "ic3po.py", line 179, in main
    raise Exception("ic3po error: return code %d" % retcode)
Exception: ic3po error: return code 1
```

**Comment by aman-goel** [comment]
@kenmcmil Thanks for raising the issue. Commit https://github.com/aman-goel/ic3po/commit/026d4da27051eff3106b7e92d33ddbc862b14e5b should fix this error. Please feel free to reopen this issue if you still see an error on your end.
